name: Merge hotfix branch
on:
  schedule:
    - cron: "0 2 * * *"
  workflow_dispatch:
jobs:
  merge:
    if: github.ref == 'ref/heads/hotfix'
    name: Merge hotfix to production
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          lfs: true

      - name: Merge hotfix into staging
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: hotfix
          target_branch: staging
          github_token: ${{ github.token }}
